### ISSUE TITLE
模块Layers 疑问

### ISSUE THREAD

**Issue by leigegege** [B-Xi/TNNLS_2022_X-GPN#1]
请问你的主函数里面,调包的时候用到 layers这个包,为什么我找不到,这个是你自己写的吗?
#from layers.centers import Centersy
#from layers.graph import GraphConvolution

**Comment by B-Xi** [comment]
你好，layers代码已上传，请下载使用，谢谢。

**Comment by leigegege** [comment]
感谢您的回复，还有一个问题，就是我也看了你之前的文章关于SSGPN的，这个里面也有layers模块，是不是和这个X-GPN的不同呀，如果是的话，是否可以再上传SSGPN的呢，只用来学习使用，万分感谢。

**Comment by B-Xi** [comment]
之前漏掉了，多谢提醒！已经上传，谢谢您关注我们的工作！
